version: '3.8'

services:
    backend:
      build:
        context: ./backend
        dockerfile: Dockerfile
      container_name: back-shortener
      environment:
        - NODE_ENV=production
        - REDIS_URL=redis:url
      ports:
        - 4002:4002

    cache:
      image: redis/redis-stack
      container_name: db-shortener
      restart: always
      ports:
          - 6379:6379
      volumes:
          - ./database:/data
volumes:
  database:
      
