version: '3.8'

services:
    backend:
      build:
        context: ./backend
        dockerfile: Dockerfile.dev
      container_name: back-shortener
      restart: always
      environment:
        - NODE_ENV=development
        - REDIS_URL=url:redis
      ports:
        - 4002:4002
      working_dir: /usr/backend/app
      volumes:
        - ./backend:/usr/backend/app
        - /usr/backend/app/node_modules
      command: npm run dev

    frontend:
        build:
          context: ./frontend
          dockerfile: Dockerfile.dev
        container_name: front-shortener
        environment:
          - VITE_BASE_URL= https://shortener.delairis.com
          - VITE_BASE_URL_DEV=http://localhost:4002
          - VITE_SELF_URL_DEV=http://localhost:3002
          - VITE_NODE_ENV=development
        restart: always
        ports:
          - 3002:3002
        working_dir: /usr/src/app
        volumes:
          - ./frontend:/usr/src/app
          - /usr/src/app/node_modules
        command: npm run dev

    cache:
      image: redis/redis-stack
      container_name: db-shortener
      restart: always
      ports:
          - 6379:6379
      volumes:
          - ./database:/data
volumes:
  database:
      
      
